### ISSUE TITLE
Bug in shaders.cpp

### ISSUE THREAD

**Issue by Liamdev631** [broughtong/OpenGL-Utils#1]
Hey I spotted a bug that was causing my app to crash. In shaders.cpp starting at line 242 when you detach the shaders, before detaching each shader you incorrectly always check if vFile != 0. I changed them to the corresponding file names and it runs fine. Also, its generally more concise to use if (vFile)  or if (vFile != nullptr)

**Comment by broughtong** [comment]
Woah...this code hasn't been touched in a longggg time! To be honest I didn't realise anyone was actually getting any use out of it. Yes of course, you are completely correct. I'll update it as you suggested.

**Comment by Liamdev631** [comment]
Lol. I went through half a dozen helper classes and yours is the only
modern one. It's the second result on google. Thanks!!!
